<?php

namespace Admingenerator\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducerRepository extends EntityRepository
{
}